---
title: "TrabajoFinal"
author: "Alejandro Ramos Usaj, Agostina Sacson y Iair Embon"
date: '2022-07-25'
output: html_document
---

Cargo los datos
```{r}
# voy a la carpeta del proyecto
root <- rprojroot::is_rstudio_project
basename(getwd())

# load the function to get the df list
source(root$find_file("Entrega_Final/df_total_filtered.Rda")) ## me tira un error aca, no se poque lo voy a esta resolviendo

load("~/Documents/Investigación/Curso.DS.R/Entrega_Final/df_total_filtered.Rda")
```

Lo exploro
```{r}
str(df_total)
```

Veo la cantidad de participantes
```{r}
print(length(unique(df_total$Participant)))
```


Exploro la variable de interes (Confianza)
```{r}
hist(df_total$confidence_key)
```

Convierto el df por trials en un df por participantes
```{r}
library(dplyr)

d <- df_total %>%
  select(!c(RelyOn,
            Problems,
            ConfKey1,
            ConfKey2,
            ConfKey3,
            ConfKey4,
            discrimination_is_correct,
            confidence_key,
            trials,
            PointDifference,
            ReacTime_DiscTask,
            ReacTime_ConfTask)) %>%
  distinct(Participant,.keep_all = TRUE)
```

Exploro la otra variable de interes (metacognicion)
```{r}
plot(density(d$mc))
```
